# generated by datamodel-codegen:
#   filename:  joshua-saati-state.json
#   timestamp: 2022-01-04T03:08:04+00:00

from __future__ import annotations
from typing import List, Optional
from pydantic import BaseModel
from sqlmodel import Field, SQLModel
from datetime import datetime
from typing import Optional
from sqlmodel import Field, Session, SQLModel, create_engine

#Generated using datamodel-codegen --input joshua-saati-state.json --input-file-type json --output model4.py


# #class Events(BaseModel):
# class Events(SQLModel, table=True):
#     id: Optional[int] = Field(default=None, primary_key=True)
#     responses: List[str]
#     sentiment: Optional[int] = None
#     sync_ratio: float
#     incoming_msg: str
#     interactions: int
#     positive_interactions: int
#     negative_interactions: int
#     level_counter: int
#     response_sentiment: str
#     timestamp: datetime.time
#     identifier: str
#     origin: str
#     situation_prompt: Optional[str] = None
#     sentiment_agent: Optional[int] = None
#     utterance_agent: Optional[str] = None


# class Model(BaseModel):
#     id: Optional[int] = Field(default=None, primary_key=True)
#     EventLog : List[Events]

# class User(BaseModel):
#     username: str
#     email: Optional[str] = None
#     full_name: Optional[str] = None
#     disabled: Optional[bool] = None

# class Agent(BaseModel):
#     uuid: UUID
#     utterances: List[str] = []
#     sentiment: float
#     sync_ratio: float
#     state: enum.Enum


# class Event(BaseModel):
#     ts: datetime = None
#     uuid: UUID = None

#     utterance_user: str
#     utterance_agent: str

#     sentiment_user: Dict
#     sentiment_agent: Dict

#     @validator("uuid", pre=True, always=True)
#     def set_id(cls, v):
#         return v or uuid4()

#     @validator("ts", pre=True, always=True)
#     def set_ts_now(cls, v):
#         return v or datetime.now()



class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: Optional[int] = None

def main():
    hero_1 = Hero(name="Deadpond", secret_name="Dive Wilson")
    hero_2 = Hero(name="Spider-Boy", secret_name="Pedro Parqueador")
    hero_3 = Hero(name="Rusty-Man", secret_name="Tommy Sharp", age=48)


    engine = create_engine("sqlite:///database.db")


    SQLModel.metadata.create_all(engine)

    with Session(engine) as session:
        session.add(hero_1)
        session.add(hero_2)
        session.add(hero_3)
        session.commit()
    breakpoint()
